# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Guild Sports Management
sass:
  style: compressed
# Build settings
markdown: kramdown
exclude: [node_modules]

#these came by default, not sure if will use
email: info@guildsports.com
description: Guild Sports Management is a sports management company for track and field athletes all around the globe.
keywords: guild sports management, guild sports, track and field, athletics, 100m, 200m, 400m, long jump, triple jump, high jump, pole vault, shot put, discus, javelin, hammer throw
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://guildsports.com" # the base hostname & protocol for your site
